      - name: SSH & Deploy to EC2 with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-65-2-6-210.ap-south-1.compute.amazonaws.com << 'EOF'
            cd ~
            if [ -d "ec2_esg_api_esg_jwt" ]; then
              cd ec2_esg_api_esg_jwt
              git pull origin master
            else
              git clone https://github.com/varunkareti22/Esg_Api.git ec2_esg_api_esg_jwt
              cd ec2_esg_api_esg_jwt
            fi
            cd ec2_esg_api_esg_jwt  # 👈 go inside the nested folder where the real files are

            echo "✅ Now in: \$(pwd)"
            ls -la docker-compose.yml
            docker-compose down || true
            docker-compose up --build -d
          EOF
