- name: SSH & Deploy to EC2 with Docker Compose
  run: |
    ssh -o StrictHostKeyChecking=no ubuntu@ec2-65-2-6-210.ap-south-1.compute.amazonaws.com << 'EOF'
      sudo apt update -y
      sudo apt install docker-compose -y
      cd ~
      if [ -d "ec2_esg_api_esg_jwt" ]; then
        cd ec2_esg_api_esg_jwt
        git pull origin master
      else
        git clone https://github.com/varunkareti22/Esg_Api.git ec2_esg_api_esg_jwt
        cd ec2_esg_api_esg_jwt
      fi
      docker-compose down || true
      docker-compose up --build -d
    EOF
