      - name: SSH & Deploy to EC2 with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-65-2-6-210.ap-south-1.compute.amazonaws.com << 'EOF'
            cd ~
            if [ -d "Esg_Api" ]; then
              cd Esg_Api
              git pull origin master
            else
              git clone https://github.com/varunkareti22/Esg_Api.git
              cd Esg_Api
            fi
            docker-compose down || true
            docker-compose up --build -d
          EOF
